-- MySQL Script generated by MySQL Workbench
-- 05/20/18 19:59:53
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sampleemailserver
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sampleemailserver
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sampleemailserver` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `sampleemailserver` ;

-- -----------------------------------------------------
-- Table `sampleemailserver`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sampleemailserver`.`user` (
  `username` (16) NOT NULL COMMENT '',
  `email` (255) NOT NULL COMMENT '',
  `password` (32) NOT NULL COMMENT '',
  `create_time`  NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`email`)  COMMENT '');


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
